
package br.edu.materdei.tas.desktop.view;

import br.edu.materdei.tas.desktop.dialog.CompraDialog;
import br.edu.materdei.tas.desktop.dialog.GenericDialogImpl;

import br.edu.materdei.tas.desktop.gui.core.TasDialogError;
import br.edu.materdei.tas.desktop.gui.core.TasItemToolBar;
import br.edu.materdei.tas.desktop.service.BackendService;

import java.awt.Cursor;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.sf.json.JSONArray;
import net.sf.json.JSONObject;

public class CompraView extends GenericView {
    private Object[] compras;

    public CompraView() {
        initComponents();
        
        //Imagens da Toolbar
        toolbar.setImage(new ImageIcon(getClass().getResource("/assets/toolbar/fundoToolbar.png")).getImage());
        btIncluir.setIcon(new ImageIcon(getClass().getResource("/assets/toolbar/incluir.png")));        
        btExcluir.setIcon(new ImageIcon(getClass().getResource("/assets/toolbar/excluir.png")));
                
        //Oculta
        acaoCompra.setVisible(false);
        
        ListSelectionModel cellSelectionModel = grid.getSelectionModel();
        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                boolean selecionado = grid.getSelectedRow() >= 0;
                btExcluir.setEnabled(selecionado);
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new br.edu.materdei.tas.desktop.gui.core.TasImagePanel();
        acaoCompra = new javax.swing.JPanel();
        tbCompra = new javax.swing.JPanel();
        btCompra = new br.edu.materdei.tas.desktop.gui.core.TasItemToolBar();
        tasSeparadorItem2 = new br.edu.materdei.tas.desktop.gui.core.TasSeparadorItem();
        btOutro = new br.edu.materdei.tas.desktop.gui.core.TasItemToolBar();
        divRight1 = new javax.swing.JPanel();
        labelCompra = new javax.swing.JLabel();
        acaoCadastro = new javax.swing.JPanel();
        toolBar = new javax.swing.JPanel();
        btIncluir = new br.edu.materdei.tas.desktop.gui.core.TasItemToolBar();
        tasSeparadorItem1 = new br.edu.materdei.tas.desktop.gui.core.TasSeparadorItem();
        btExcluir = new br.edu.materdei.tas.desktop.gui.core.TasItemToolBar();
        divRight = new javax.swing.JPanel();
        labelAcaoMenu = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        tabTop = new javax.swing.JPanel();
        tabLeft = new javax.swing.JPanel();
        tabRight = new javax.swing.JPanel();
        tabBottom = new javax.swing.JPanel();
        conteudo = new javax.swing.JPanel();
        panelMigalha = new javax.swing.JPanel();
        migalha = new javax.swing.JLabel();
        panelTabela = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        grid = new javax.swing.JTable();

        setBackground(new java.awt.Color(246, 246, 246));
        setLayout(new java.awt.BorderLayout());

        toolbar.setMaximumSize(new java.awt.Dimension(32767, 103));
        toolbar.setMinimumSize(new java.awt.Dimension(0, 103));
        toolbar.setPreferredSize(new java.awt.Dimension(540, 103));
        toolbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 4));

        acaoCompra.setMinimumSize(new java.awt.Dimension(155, 99));
        acaoCompra.setOpaque(false);
        acaoCompra.setPreferredSize(new java.awt.Dimension(118, 99));
        acaoCompra.setLayout(new java.awt.BorderLayout());

        tbCompra.setMaximumSize(new java.awt.Dimension(32767, 78));
        tbCompra.setMinimumSize(new java.awt.Dimension(57, 78));
        tbCompra.setOpaque(false);
        tbCompra.setPreferredSize(new java.awt.Dimension(57, 78));
        tbCompra.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 0, 0));

        btCompra.setToolTipText("Cadastro de Compra");
        btCompra.setLabel("Compras");
        btCompra.setMaximumSize(new java.awt.Dimension(52, 78));
        btCompra.setMinimumSize(new java.awt.Dimension(52, 78));
        btCompra.setPreferredSize(new java.awt.Dimension(52, 78));
        btCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCompraMousePressed(evt);
            }
        });
        tbCompra.add(btCompra);

        javax.swing.GroupLayout tasSeparadorItem2Layout = new javax.swing.GroupLayout(tasSeparadorItem2);
        tasSeparadorItem2.setLayout(tasSeparadorItem2Layout);
        tasSeparadorItem2Layout.setHorizontalGroup(
            tasSeparadorItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        tasSeparadorItem2Layout.setVerticalGroup(
            tasSeparadorItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        tbCompra.add(tasSeparadorItem2);

        btOutro.setToolTipText("...");
        btOutro.setDoubleBuffered(false);
        btOutro.setLabel("...");
        btOutro.setMaximumSize(new java.awt.Dimension(52, 78));
        btOutro.setMinimumSize(new java.awt.Dimension(52, 78));
        btOutro.setPreferredSize(new java.awt.Dimension(52, 78));
        tbCompra.add(btOutro);

        acaoCompra.add(tbCompra, java.awt.BorderLayout.CENTER);

        divRight1.setBackground(new java.awt.Color(198, 198, 198));
        divRight1.setPreferredSize(new java.awt.Dimension(1, 100));

        javax.swing.GroupLayout divRight1Layout = new javax.swing.GroupLayout(divRight1);
        divRight1.setLayout(divRight1Layout);
        divRight1Layout.setHorizontalGroup(
            divRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        divRight1Layout.setVerticalGroup(
            divRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        acaoCompra.add(divRight1, java.awt.BorderLayout.EAST);

        labelCompra.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        labelCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCompra.setText("Compra e ...");
        labelCompra.setMaximumSize(new java.awt.Dimension(101, 21));
        labelCompra.setMinimumSize(new java.awt.Dimension(101, 21));
        labelCompra.setPreferredSize(new java.awt.Dimension(101, 21));
        acaoCompra.add(labelCompra, java.awt.BorderLayout.SOUTH);

        toolbar.add(acaoCompra);

        acaoCadastro.setMinimumSize(new java.awt.Dimension(155, 99));
        acaoCadastro.setOpaque(false);
        acaoCadastro.setPreferredSize(new java.awt.Dimension(118, 99));
        acaoCadastro.setLayout(new java.awt.BorderLayout());

        toolBar.setMaximumSize(new java.awt.Dimension(32767, 78));
        toolBar.setMinimumSize(new java.awt.Dimension(57, 78));
        toolBar.setOpaque(false);
        toolBar.setPreferredSize(new java.awt.Dimension(57, 78));
        toolBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 0, 0));

        btIncluir.setToolTipText("Novo Produto");
        btIncluir.setLabel("Incluir");
        btIncluir.setMaximumSize(new java.awt.Dimension(52, 78));
        btIncluir.setMinimumSize(new java.awt.Dimension(52, 78));
        btIncluir.setPreferredSize(new java.awt.Dimension(52, 78));
        btIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btIncluirMousePressed(evt);
            }
        });
        toolBar.add(btIncluir);

        javax.swing.GroupLayout tasSeparadorItem1Layout = new javax.swing.GroupLayout(tasSeparadorItem1);
        tasSeparadorItem1.setLayout(tasSeparadorItem1Layout);
        tasSeparadorItem1Layout.setHorizontalGroup(
            tasSeparadorItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        tasSeparadorItem1Layout.setVerticalGroup(
            tasSeparadorItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        toolBar.add(tasSeparadorItem1);

        btExcluir.setToolTipText("Excluir Produto");
        btExcluir.setDoubleBuffered(false);
        btExcluir.setLabel("Excluir");
        btExcluir.setMaximumSize(new java.awt.Dimension(52, 78));
        btExcluir.setMinimumSize(new java.awt.Dimension(52, 78));
        btExcluir.setPreferredSize(new java.awt.Dimension(52, 78));
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExcluirMousePressed(evt);
            }
        });
        toolBar.add(btExcluir);

        acaoCadastro.add(toolBar, java.awt.BorderLayout.CENTER);

        divRight.setBackground(new java.awt.Color(198, 198, 198));
        divRight.setPreferredSize(new java.awt.Dimension(1, 100));

        javax.swing.GroupLayout divRightLayout = new javax.swing.GroupLayout(divRight);
        divRight.setLayout(divRightLayout);
        divRightLayout.setHorizontalGroup(
            divRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        divRightLayout.setVerticalGroup(
            divRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        acaoCadastro.add(divRight, java.awt.BorderLayout.EAST);

        labelAcaoMenu.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        labelAcaoMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAcaoMenu.setText("Ações de Cadastros");
        labelAcaoMenu.setMaximumSize(new java.awt.Dimension(101, 21));
        labelAcaoMenu.setMinimumSize(new java.awt.Dimension(101, 21));
        labelAcaoMenu.setPreferredSize(new java.awt.Dimension(101, 21));
        acaoCadastro.add(labelAcaoMenu, java.awt.BorderLayout.SOUTH);

        toolbar.add(acaoCadastro);

        add(toolbar, java.awt.BorderLayout.NORTH);

        container.setBackground(new java.awt.Color(246, 246, 246));
        container.setLayout(new java.awt.BorderLayout());

        tabTop.setOpaque(false);
        tabTop.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout tabTopLayout = new javax.swing.GroupLayout(tabTop);
        tabTop.setLayout(tabTopLayout);
        tabTopLayout.setHorizontalGroup(
            tabTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        tabTopLayout.setVerticalGroup(
            tabTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        container.add(tabTop, java.awt.BorderLayout.NORTH);

        tabLeft.setOpaque(false);
        tabLeft.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout tabLeftLayout = new javax.swing.GroupLayout(tabLeft);
        tabLeft.setLayout(tabLeftLayout);
        tabLeftLayout.setHorizontalGroup(
            tabLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        tabLeftLayout.setVerticalGroup(
            tabLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        container.add(tabLeft, java.awt.BorderLayout.WEST);

        tabRight.setOpaque(false);
        tabRight.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout tabRightLayout = new javax.swing.GroupLayout(tabRight);
        tabRight.setLayout(tabRightLayout);
        tabRightLayout.setHorizontalGroup(
            tabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        tabRightLayout.setVerticalGroup(
            tabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        container.add(tabRight, java.awt.BorderLayout.EAST);

        tabBottom.setOpaque(false);
        tabBottom.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout tabBottomLayout = new javax.swing.GroupLayout(tabBottom);
        tabBottom.setLayout(tabBottomLayout);
        tabBottomLayout.setHorizontalGroup(
            tabBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        tabBottomLayout.setVerticalGroup(
            tabBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        container.add(tabBottom, java.awt.BorderLayout.SOUTH);

        conteudo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 215, 222)));
        conteudo.setOpaque(false);
        conteudo.setLayout(new java.awt.BorderLayout());

        panelMigalha.setBackground(new java.awt.Color(252, 252, 252));
        panelMigalha.setPreferredSize(new java.awt.Dimension(388, 28));
        panelMigalha.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        migalha.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        migalha.setText("Cadastro de Compras");
        panelMigalha.add(migalha);

        conteudo.add(panelMigalha, java.awt.BorderLayout.NORTH);

        panelTabela.setOpaque(false);

        scroll.setBackground(new java.awt.Color(246, 246, 246));

        grid.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        grid.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        grid.setGridColor(new java.awt.Color(240, 240, 240));
        grid.setRowHeight(22);
        grid.setSelectionBackground(new java.awt.Color(50, 153, 255));
        grid.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        grid.setShowVerticalLines(false);
        grid.getTableHeader().setResizingAllowed(false);
        scroll.setViewportView(grid);

        javax.swing.GroupLayout panelTabelaLayout = new javax.swing.GroupLayout(panelTabela);
        panelTabela.setLayout(panelTabelaLayout);
        panelTabelaLayout.setHorizontalGroup(
            panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        panelTabelaLayout.setVerticalGroup(
            panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        conteudo.add(panelTabela, java.awt.BorderLayout.CENTER);

        container.add(conteudo, java.awt.BorderLayout.CENTER);

        add(container, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIncluirMousePressed
        TasItemToolBar item = (TasItemToolBar) evt.getComponent();
        if (item.isEnabled()) {
            this.incluir();
        }
    }//GEN-LAST:event_btIncluirMousePressed

    private void btExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMousePressed
        TasItemToolBar item = (TasItemToolBar) evt.getComponent();
        if (item.isEnabled()) {
            this.excluir();
        }
    }//GEN-LAST:event_btExcluirMousePressed

    private void btCompraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCompraMousePressed
        this.preparaCompra();
    }//GEN-LAST:event_btCompraMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acaoCadastro;
    private javax.swing.JPanel acaoCompra;
    private br.edu.materdei.tas.desktop.gui.core.TasItemToolBar btCompra;
    private br.edu.materdei.tas.desktop.gui.core.TasItemToolBar btExcluir;
    private br.edu.materdei.tas.desktop.gui.core.TasItemToolBar btIncluir;
    private br.edu.materdei.tas.desktop.gui.core.TasItemToolBar btOutro;
    private javax.swing.JPanel container;
    private javax.swing.JPanel conteudo;
    private javax.swing.JPanel divRight;
    private javax.swing.JPanel divRight1;
    private javax.swing.JTable grid;
    private javax.swing.JLabel labelAcaoMenu;
    private javax.swing.JLabel labelCompra;
    private javax.swing.JLabel migalha;
    private javax.swing.JPanel panelMigalha;
    private javax.swing.JPanel panelTabela;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JPanel tabBottom;
    private javax.swing.JPanel tabLeft;
    private javax.swing.JPanel tabRight;
    private javax.swing.JPanel tabTop;
    private br.edu.materdei.tas.desktop.gui.core.TasSeparadorItem tasSeparadorItem1;
    private br.edu.materdei.tas.desktop.gui.core.TasSeparadorItem tasSeparadorItem2;
    private javax.swing.JPanel tbCompra;
    private javax.swing.JPanel toolBar;
    private br.edu.materdei.tas.desktop.gui.core.TasImagePanel toolbar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void preinit() {
        preparaCompra();
    }
    private void preparaCompra() {
        
        //Tabela
        constroiTabelaCompra();
        
        //Carrega dados
        loadDados();
        
        //Carrega dados no grid
        carregaGridCompra();
        
    }
    
    private void constroiTabelaCompra() {
        //Monta tabela
        grid.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        DefaultTableModel modelo = (DefaultTableModel) grid.getModel();
        modelo.setColumnCount(0);
        
        //Define o título das colunas
        modelo.addColumn("Código");
        modelo.addColumn("Data");
        modelo.addColumn("Fornecedor");
        modelo.addColumn("Total (R$)");
        
        //Define largura das colunas
        grid.getColumnModel().getColumn(0).setPreferredWidth(100);
        grid.getColumnModel().getColumn(1).setPreferredWidth(150);
        grid.getColumnModel().getColumn(2).setPreferredWidth(450);
        grid.getColumnModel().getColumn(3).setPreferredWidth(300);
        
        mainframe.setStatus("Pronto!");        
    }
    
    public void loadDados() {
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        try {
            mainframe.setStatus("Carregando dados. Aguarde...");
            
            try {
                this.compras = BackendService.findAll("compras");

                mainframe.setStatus("Pronto!");   
            } catch (Exception e) {
                TasDialogError dlgError = new TasDialogError(mainframe);
                dlgError.showError(TasDialogError.DANGER_ERROR, 
                                   "<html>Não foi possível carregar os registros. Clique em \"Detalhes\" Para visualizar o problema.</html>", 
                                   e.getMessage());
                this.mainframe.setStatus(new ImageIcon(getClass().getResource("/assets/system/icons/icon-warning-small.png")), 
                                         e.getMessage(), "Ops!");
            }
        } finally {
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }
    
    private Double getTotal(JSONObject compra) {
        Double total = 0.0;
        
        JSONArray itens = (JSONArray) compra.getJSONArray("itens");
        
        for (Object object : itens.toArray()) {
            JSONObject item = (JSONObject) object;
            
            total += (item.getDouble("vlrunit") * item.getDouble("qtdade"));
        }
        
        return total;
    }
    private void carregaGridCompra() {
        DefaultTableModel modelo = (DefaultTableModel) grid.getModel();
        
        mainframe.setStatus("Carregando dados no grid. Aguarde...");
        
        try {
            //Alimenta a tabela
            modelo.setNumRows(0);
            for (Object dado : this.compras) {
                JSONObject compra = (JSONObject) dado;

                Date dtcompra = new SimpleDateFormat("yyyy-MM-dd").parse(compra.getString("dtcompra"));
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                NumberFormat nf = NumberFormat.getCurrencyInstance();
                String total = nf.format(getTotal(compra));

                JSONObject fornecedor = (JSONObject) compra.get("fornecedor");

                modelo.addRow(new Object[] {compra.getString("codigo"), sdf.format(dtcompra),
                                            fornecedor.getString("nome"), total});
            }
            grid.setModel(modelo);
        } catch (ParseException ex) {
            TasDialogError dlgError = new TasDialogError(mainframe);
            dlgError.showError(TasDialogError.DANGER_ERROR, 
                    "<html>Não foi possível formatar a Data da Compra. Clique em \"Detalhes\" Para visualizar o problema.</html>", 
                    ex.getMessage());
            
            this.mainframe.setStatus(new ImageIcon(getClass().getResource("/assets/system/icons/icon-warning-small.png")), 
                    ex.getMessage(), "Ops!");
        }            
        
        mainframe.setStatus("Pronto!");
    }
    
    private void showDialogCompra(JSONObject compra){
        CompraDialog dialog = new CompraDialog(mainframe, compra);
        showDialog(dialog);
        
        if (!dialog.fail) {
            loadDados();
            carregaGridCompra();
        }       
    }
    private void showDialog(GenericDialogImpl dialog) {
        getRootPane().getGlassPane().setVisible(true);
        
        dialog.dispose();
        dialog.setLocationRelativeTo(this);
        dialog.setUndecorated(true);
        dialog.setVisible(true);
        
        getRootPane().getGlassPane().setVisible(false);
    }
    
    //TOOLBAR
    private void incluir() {
        JSONObject compra = new JSONObject();
        compra.put("codigo", "");
        compra.put("dtcompra", "");
        compra.put("fornecedor", null);
        compra.put("itens", null);        
        
        showDialogCompra(compra);
    }
    private void excluir() {
        Object[] options = { "Sim", "Não" };
        
        int opcao = JOptionPane.showOptionDialog(this, "Deseja excluir o registro selecionado?", 
                                                 "Excluir registro", JOptionPane.YES_NO_OPTION, 
                                                 JOptionPane.QUESTION_MESSAGE, null,  
                                                 options, options[0]);
        if (opcao == JOptionPane.YES_OPTION) {
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            try {
                mainframe.setStatus("Excluindo registro. Aguarde...");
                try {
                    JSONObject compra = (JSONObject) this.compras[grid.getSelectedRow()];
                    BackendService.deleteById("compras/"+ compra.get("id"));
                    loadDados();
                    carregaGridCompra();                    
                    
                } catch (Exception e) {
                    TasDialogError dlgError = new TasDialogError(mainframe);
                    dlgError.showError(TasDialogError.DANGER_ERROR, 
                                       "<html>Não foi possível excluir o registro. Clique em \"Detalhes\" Para visualizar o problema.</html>", 
                                       e.getMessage());
                    this.mainframe.setStatus(new ImageIcon(getClass().getResource("/assets/system/icons/icon-warning-small.png")), 
                                             e.getMessage(), "Ops!");
                }                
            } finally {
                setCursor(new Cursor(Cursor.DEFAULT_CURSOR));    
            }
        }
    }    
}
