package br.edu.materdei.tas.desktop.view;

import br.edu.materdei.tas.desktop.MainFrame;
import java.text.ParseException;
import javax.swing.JPanel;
import javax.swing.text.MaskFormatter;


public class GenericView extends JPanel {
    protected MainFrame mainframe;
    
    /**
     * Creates new form GenericView
     */
    public GenericView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void setMainFrame(MainFrame mainframe) {
        this.mainframe = mainframe;
    }

    public void preinit() {}
    
    protected static String format(String pattern, Object value) {
        MaskFormatter mask;
        try {
            mask = new MaskFormatter(pattern);
            mask.setValueContainsLiteralCharacters(false);
            return mask.valueToString(value);
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
    }
}
