package br.edu.materdei.tas.desktop.gui.titlebar;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class TasCloseButton extends JPanel {
    private final Color colorOn = new Color(253,229,221);
    private final Color colorOff = new Color(246,246,246);
    
    private final ImageIcon iconOff;
    private final ImageIcon iconOn;

    /**
     * Creates new form TasCloseButton
     */
    public TasCloseButton() {
        initComponents();
        
        iconOff = new ImageIcon(getClass().getResource("/assets/system/titlebar/cloOff.png"));
        iconOn = new ImageIcon(getClass().getResource("/assets/system/titlebar/cloOn.png"));
        
        icone.setIcon(iconOff);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icone = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 246, 246));
        setToolTipText("Fechar");
        setMaximumSize(new java.awt.Dimension(35, 21));
        setMinimumSize(new java.awt.Dimension(35, 21));
        setPreferredSize(new java.awt.Dimension(35, 21));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());
        add(icone, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        setBackground(colorOn);
        icone.setIcon(iconOn);
        java.awt.EventQueue.invokeLater(new Runnable(){     
            @Override
            public void run(){     
                revalidate();  
                repaint();     
            }              
        });
    }//GEN-LAST:event_formMouseMoved

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setBackground(colorOff);
        icone.setIcon(iconOff);
        java.awt.EventQueue.invokeLater(new Runnable(){     
            @Override
            public void run(){     
                revalidate();  
                repaint();     
            }              
        });
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icone;
    // End of variables declaration//GEN-END:variables
}
