package br.edu.materdei.tas.desktop.gui.titlebar;

import br.edu.materdei.tas.desktop.MainFrame;
import java.awt.Window;
import javax.swing.JPanel;


public class TasTitleBar extends JPanel {
    private MainFrame frame;

    /**
     * Creates new form TasTitleBar
     */
    public TasTitleBar() {
        initComponents();
        
        restaurar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        divTop = new javax.swing.JPanel();
        plLeft = new javax.swing.JPanel();
        plRight = new javax.swing.JPanel();
        divBottom = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        plBotoes = new javax.swing.JPanel();
        minimizar = new br.edu.materdei.tas.desktop.gui.titlebar.TasMinimizeButton();
        maximizar = new br.edu.materdei.tas.desktop.gui.titlebar.TasMaximizeButton();
        restaurar = new br.edu.materdei.tas.desktop.gui.titlebar.TasRestoreButton();
        close = new br.edu.materdei.tas.desktop.gui.titlebar.TasCloseButton();
        titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 246, 246));
        setMaximumSize(new java.awt.Dimension(2147483647, 34));
        setMinimumSize(new java.awt.Dimension(277, 34));
        setLayout(new java.awt.BorderLayout());

        divTop.setOpaque(false);
        divTop.setPreferredSize(new java.awt.Dimension(10, 7));

        javax.swing.GroupLayout divTopLayout = new javax.swing.GroupLayout(divTop);
        divTop.setLayout(divTopLayout);
        divTopLayout.setHorizontalGroup(
            divTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        divTopLayout.setVerticalGroup(
            divTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        add(divTop, java.awt.BorderLayout.NORTH);

        plLeft.setOpaque(false);
        plLeft.setPreferredSize(new java.awt.Dimension(5, 10));

        javax.swing.GroupLayout plLeftLayout = new javax.swing.GroupLayout(plLeft);
        plLeft.setLayout(plLeftLayout);
        plLeftLayout.setHorizontalGroup(
            plLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        plLeftLayout.setVerticalGroup(
            plLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        add(plLeft, java.awt.BorderLayout.WEST);

        plRight.setOpaque(false);
        plRight.setPreferredSize(new java.awt.Dimension(5, 10));

        javax.swing.GroupLayout plRightLayout = new javax.swing.GroupLayout(plRight);
        plRight.setLayout(plRightLayout);
        plRightLayout.setHorizontalGroup(
            plRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        plRightLayout.setVerticalGroup(
            plRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        add(plRight, java.awt.BorderLayout.EAST);

        divBottom.setOpaque(false);
        divBottom.setPreferredSize(new java.awt.Dimension(10, 6));

        javax.swing.GroupLayout divBottomLayout = new javax.swing.GroupLayout(divBottom);
        divBottom.setLayout(divBottomLayout);
        divBottomLayout.setHorizontalGroup(
            divBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        divBottomLayout.setVerticalGroup(
            divBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(divBottom, java.awt.BorderLayout.SOUTH);

        container.setOpaque(false);
        container.setPreferredSize(new java.awt.Dimension(277, 21));
        container.setLayout(new java.awt.BorderLayout());

        plBotoes.setMaximumSize(new java.awt.Dimension(105, 10));
        plBotoes.setMinimumSize(new java.awt.Dimension(105, 10));
        plBotoes.setOpaque(false);
        plBotoes.setPreferredSize(new java.awt.Dimension(105, 10));
        plBotoes.setLayout(new java.awt.GridBagLayout());

        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizarMousePressed(evt);
            }
        });
        plBotoes.add(minimizar, new java.awt.GridBagConstraints());

        maximizar.setToolTipText("Maximizar");
        maximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maximizarMousePressed(evt);
            }
        });
        plBotoes.add(maximizar, new java.awt.GridBagConstraints());

        restaurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                restaurarMousePressed(evt);
            }
        });
        plBotoes.add(restaurar, new java.awt.GridBagConstraints());

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        plBotoes.add(close, new java.awt.GridBagConstraints());

        container.add(plBotoes, java.awt.BorderLayout.EAST);

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("TASERP - Aplicação Desktop");
        container.add(titulo, java.awt.BorderLayout.CENTER);

        add(container, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        frame.fechar();
    }//GEN-LAST:event_closeMousePressed

    private void restaurarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurarMousePressed
        frame.restaurar();
        maximizar.setVisible(true);
        restaurar.setVisible(false);
    }//GEN-LAST:event_restaurarMousePressed

    private void maximizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizarMousePressed
        frame.maximizar();
        maximizar.setVisible(false);
        restaurar.setVisible(true);
    }//GEN-LAST:event_maximizarMousePressed

    private void minimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMousePressed
        frame.minimizar();
    }//GEN-LAST:event_minimizarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.edu.materdei.tas.desktop.gui.titlebar.TasCloseButton close;
    private javax.swing.JPanel container;
    private javax.swing.JPanel divBottom;
    private javax.swing.JPanel divTop;
    private br.edu.materdei.tas.desktop.gui.titlebar.TasMaximizeButton maximizar;
    private br.edu.materdei.tas.desktop.gui.titlebar.TasMinimizeButton minimizar;
    private javax.swing.JPanel plBotoes;
    private javax.swing.JPanel plLeft;
    private javax.swing.JPanel plRight;
    private br.edu.materdei.tas.desktop.gui.titlebar.TasRestoreButton restaurar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    public void setTitulo(String texto) {
        titulo.setText(texto);
    }
    public void setParent(Window parent) {
        this.frame = (MainFrame) parent;
    }
}
