package br.edu.materdei.tas.desktop;

import br.edu.materdei.tas.desktop.bean.ItemMenuBean;
import br.edu.materdei.tas.desktop.view.CompraView;
import br.edu.materdei.tas.desktop.view.GrupProdView;
import br.edu.materdei.tas.desktop.view.PedidoVendaView;
import br.edu.materdei.tas.desktop.view.PessoaView;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;



public class MainFrame extends javax.swing.JFrame {
    private Point point = new Point();
    
    /** Creates new form MainFrame
     * @param appcontext 
     */
    public MainFrame() {
        
        initComponents();
        
        //Efeito de sombra ao abrir janela modal
        getRootPane().setGlassPane(new JComponent() {
            @Override
            public void paintComponent(Graphics g) {
                g.setColor(new Color(255,255,255, 150));
                g.fillRect(0, 0, getWidth(), getHeight());
                super.paintComponent(g);
            }
        });
        
        //LookAdnFeel
        lookAndFeel();
        
        //Centraliza aplicação        
        setLocationRelativeTo(null);
        
        //Movimentar o frame pela barra de titulo
        barraTitulo.setParent(this);
        barraTitulo.addMouseListener(new MouseAdapter() {  
            @Override
            public void mousePressed(MouseEvent e) {  
                if (!e.isMetaDown()) {  
                    point.x = e.getX();  
                    point.y = e.getY();  
                }  
            }  
        });  
        barraTitulo.addMouseMotionListener(new MouseMotionAdapter() {  
            @Override
            public void mouseDragged(MouseEvent e) {  
                if (!e.isMetaDown()) {
                    Point p = getLocation();  
                    setLocation(p.x + e.getX() - point.x,  p.y + e.getY() - point.y);  
                }  
            }  
        });
        
        customComponents();
    }
    
    private void lookAndFeel() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar mudar o tema!" + erro);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        barraFerramentas = new javax.swing.JPanel();
        barraTitulo = new br.edu.materdei.tas.desktop.gui.titlebar.TasTitleBar();
        barraMenu = new br.edu.materdei.tas.desktop.gui.menuabas.TasMenuAba();
        conteudo = new javax.swing.JPanel();
        barraStatus = new javax.swing.JPanel();
        lbStatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbRelease = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));

        container.setBackground(new java.awt.Color(246, 246, 246));
        container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 64, 34)));
        container.setLayout(new java.awt.BorderLayout());

        barraFerramentas.setMaximumSize(new java.awt.Dimension(2147483647, 63));
        barraFerramentas.setMinimumSize(new java.awt.Dimension(0, 63));
        barraFerramentas.setOpaque(false);
        barraFerramentas.setPreferredSize(new java.awt.Dimension(0, 63));
        barraFerramentas.setLayout(new java.awt.BorderLayout());
        barraFerramentas.add(barraTitulo, java.awt.BorderLayout.NORTH);

        barraMenu.setMaximumSize(new java.awt.Dimension(32767, 29));
        barraMenu.setMinimumSize(new java.awt.Dimension(10, 29));
        barraMenu.setPreferredSize(new java.awt.Dimension(0, 29));
        barraMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));
        barraFerramentas.add(barraMenu, java.awt.BorderLayout.CENTER);

        container.add(barraFerramentas, java.awt.BorderLayout.NORTH);

        conteudo.setOpaque(false);
        conteudo.setLayout(new java.awt.BorderLayout());
        container.add(conteudo, java.awt.BorderLayout.CENTER);

        barraStatus.setBackground(new java.awt.Color(188, 64, 34));
        barraStatus.setPreferredSize(new java.awt.Dimension(10, 30));
        barraStatus.setLayout(new java.awt.BorderLayout());

        lbStatus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(255, 255, 255));
        barraStatus.add(lbStatus, java.awt.BorderLayout.CENTER);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(5, 10));
        barraStatus.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lbRelease.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbRelease.setForeground(new java.awt.Color(255, 255, 255));
        lbRelease.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbRelease.setText("1.0");
        lbRelease.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbRelease.setPreferredSize(new java.awt.Dimension(60, 16));
        jPanel2.add(lbRelease, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel2.add(jPanel3, java.awt.BorderLayout.EAST);

        barraStatus.add(jPanel2, java.awt.BorderLayout.EAST);

        container.add(barraStatus, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraFerramentas;
    private br.edu.materdei.tas.desktop.gui.menuabas.TasMenuAba barraMenu;
    private javax.swing.JPanel barraStatus;
    private br.edu.materdei.tas.desktop.gui.titlebar.TasTitleBar barraTitulo;
    private javax.swing.JPanel container;
    private javax.swing.JPanel conteudo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbRelease;
    private javax.swing.JLabel lbStatus;
    // End of variables declaration//GEN-END:variables

    
    private void customComponents() {
        //Menu Abas
        ArrayList<ItemMenuBean> menus = new ArrayList();
        ItemMenuBean mn1 = new ItemMenuBean("Grupos e Produtos", new GrupProdView());
        menus.add(mn1);
        ItemMenuBean mn2 = new ItemMenuBean("Pessoas", new PessoaView());
        menus.add(mn2);
        ItemMenuBean mn3 = new ItemMenuBean("Compras", new CompraView());
        menus.add(mn3);
        ItemMenuBean mn4 = new ItemMenuBean("Vendas", new PedidoVendaView());
        menus.add(mn4);
        //ItemMenuBean mn5 = new ItemMenuBean("Estoque", new GenericView());
        //menus.add(mn5);
        barraMenu.setAbas(this, menus);
        
        //Rodape
        Properties properties = new Properties();
        try {
            properties.load(this.getClass().getResourceAsStream("/project.properties"));
            lbRelease.setText(properties.getProperty("version"));
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void minimizar() {
        this.setExtendedState(JFrame.ICONIFIED);
    }
    public void restaurar() {
        this.setExtendedState(JFrame.NORMAL);
    }
    public void maximizar() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    public void fechar() {
        Object[] options = { "Sim", "Não" };
        
        int opcao = JOptionPane.showOptionDialog(this, "Deseja sair da aplicação?", 
                                                 "Saída do Aplicativo", JOptionPane.YES_NO_OPTION, 
                                                 JOptionPane.QUESTION_MESSAGE, null,  
                                                 options, options[0]);
        if (opcao == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }
    public void setStatus(String texto) {
        setStatus(null, "", texto);
    }
    public void setStatus(Icon icon, String toolTip, String texto) {
        lbStatus.setIcon(icon);
        lbStatus.setText(texto);
        lbStatus.setToolTipText(toolTip);
        
        java.awt.EventQueue.invokeLater(new Runnable(){     
            @Override
            public void run(){     
                lbStatus.revalidate();  
                lbStatus.repaint();     
            }              
        });
    }
    public void setContent(JPanel panel) {
        conteudo.removeAll();
        conteudo.add(panel, java.awt.BorderLayout.CENTER);
        java.awt.EventQueue.invokeLater(new Runnable(){     
            @Override
            public void run(){     
                conteudo.revalidate();  
                conteudo.repaint();     
            }              
        });
    }

}
