package br.edu.materdei.tas.desktop.dialog;

import br.edu.materdei.tas.desktop.MainFrame;
import br.edu.materdei.tas.desktop.exception.NotValidateException;
import br.edu.materdei.tas.desktop.gui.core.CNPJDocument;
import br.edu.materdei.tas.desktop.gui.core.TasDialogError;
import br.edu.materdei.tas.desktop.service.BackendService;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import net.sf.json.JSONObject;


public class FornecedorDialog extends GenericDialogImpl {
    private JSONObject fornecedor;
    
    /**
     * Creates new form TasDialogConfirm
     * @param parent
     * @param fornecedor
     */
    public FornecedorDialog(java.awt.Frame parent, JSONObject fornecedor) {
        super(parent, true);
        
        this.mainframe = (MainFrame) parent;
        this.fieldsEmpty = new ArrayList<>();
        
        initComponents();
        
        tfCNPJ.setDocument(new CNPJDocument());
        
        setFornecedor(fornecedor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        barraTitulo = new javax.swing.JPanel();
        divTop = new javax.swing.JPanel();
        plLeft = new javax.swing.JPanel();
        plRight = new javax.swing.JPanel();
        divBottom = new javax.swing.JPanel();
        container1 = new javax.swing.JPanel();
        close = new br.edu.materdei.tas.desktop.gui.titlebar.TasCloseButton();
        titulo = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        tfCodigo = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfCNPJ = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfContato = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botoes = new javax.swing.JPanel();
        cancelar = new br.edu.materdei.tas.desktop.gui.core.TasDialogButton();
        salvar = new br.edu.materdei.tas.desktop.gui.core.TasDialogButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        container.setBackground(new java.awt.Color(246, 246, 246));
        container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 64, 34)));
        container.setLayout(new java.awt.BorderLayout());

        barraTitulo.setOpaque(false);
        barraTitulo.setPreferredSize(new java.awt.Dimension(348, 34));
        barraTitulo.setLayout(new java.awt.BorderLayout());

        divTop.setOpaque(false);
        divTop.setPreferredSize(new java.awt.Dimension(10, 7));

        javax.swing.GroupLayout divTopLayout = new javax.swing.GroupLayout(divTop);
        divTop.setLayout(divTopLayout);
        divTopLayout.setHorizontalGroup(
            divTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );
        divTopLayout.setVerticalGroup(
            divTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        barraTitulo.add(divTop, java.awt.BorderLayout.NORTH);

        plLeft.setOpaque(false);
        plLeft.setPreferredSize(new java.awt.Dimension(5, 10));

        javax.swing.GroupLayout plLeftLayout = new javax.swing.GroupLayout(plLeft);
        plLeft.setLayout(plLeftLayout);
        plLeftLayout.setHorizontalGroup(
            plLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        plLeftLayout.setVerticalGroup(
            plLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        barraTitulo.add(plLeft, java.awt.BorderLayout.WEST);

        plRight.setOpaque(false);
        plRight.setPreferredSize(new java.awt.Dimension(5, 10));

        javax.swing.GroupLayout plRightLayout = new javax.swing.GroupLayout(plRight);
        plRight.setLayout(plRightLayout);
        plRightLayout.setHorizontalGroup(
            plRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        plRightLayout.setVerticalGroup(
            plRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        barraTitulo.add(plRight, java.awt.BorderLayout.EAST);

        divBottom.setOpaque(false);
        divBottom.setPreferredSize(new java.awt.Dimension(10, 6));

        javax.swing.GroupLayout divBottomLayout = new javax.swing.GroupLayout(divBottom);
        divBottom.setLayout(divBottomLayout);
        divBottomLayout.setHorizontalGroup(
            divBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );
        divBottomLayout.setVerticalGroup(
            divBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        barraTitulo.add(divBottom, java.awt.BorderLayout.SOUTH);

        container1.setOpaque(false);
        container1.setPreferredSize(new java.awt.Dimension(277, 21));
        container1.setLayout(new java.awt.BorderLayout());

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        container1.add(close, java.awt.BorderLayout.EAST);

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Cadastro de Fornecedor");
        container1.add(titulo, java.awt.BorderLayout.CENTER);

        barraTitulo.add(container1, java.awt.BorderLayout.CENTER);

        container.add(barraTitulo, java.awt.BorderLayout.NORTH);

        content.setOpaque(false);

        tfCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfCNPJ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfContato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("CNPJ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("E-mail");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("Contato");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNome)
                    .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 235, Short.MAX_VALUE))
                    .addComponent(tfContato))
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        container.add(content, java.awt.BorderLayout.CENTER);

        botoes.setOpaque(false);
        botoes.setPreferredSize(new java.awt.Dimension(10, 50));
        botoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 10, 10));

        cancelar.setButtonType(br.edu.materdei.tas.desktop.gui.core.TasDialogButton.DialogButtonType.DANGER_BUTTON);
        cancelar.setLabel("Cancelar");
        cancelar.setPreferredSize(new java.awt.Dimension(75, 30));
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarMousePressed(evt);
            }
        });
        botoes.add(cancelar);

        salvar.setButtonType(br.edu.materdei.tas.desktop.gui.core.TasDialogButton.DialogButtonType.SUCCESS_BUTTON);
        salvar.setLabel("Salvar");
        salvar.setPreferredSize(new java.awt.Dimension(75, 30));
        salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salvarMousePressed(evt);
            }
        });
        botoes.add(salvar);

        container.add(botoes, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMousePressed
        dispose();
    }//GEN-LAST:event_cancelarMousePressed

    private void salvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMousePressed
        try {
            validarDados();
            salvar();
        } catch (NotValidateException e) {
            TasDialogError dlgWarning = new TasDialogError(mainframe);
            dlgWarning.showError(TasDialogError.WARNING_ERROR, 
                                 "Preenchimento obrigatório", 
                                 e.getMessage(), 
                                 this.fieldsEmpty);
        }
    }//GEN-LAST:event_salvarMousePressed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        dispose();
    }//GEN-LAST:event_closeMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraTitulo;
    private javax.swing.JPanel botoes;
    private br.edu.materdei.tas.desktop.gui.core.TasDialogButton cancelar;
    private br.edu.materdei.tas.desktop.gui.titlebar.TasCloseButton close;
    private javax.swing.JPanel container;
    private javax.swing.JPanel container1;
    private javax.swing.JPanel content;
    private javax.swing.JPanel divBottom;
    private javax.swing.JPanel divTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel plLeft;
    private javax.swing.JPanel plRight;
    private br.edu.materdei.tas.desktop.gui.core.TasDialogButton salvar;
    private javax.swing.JTextField tfCNPJ;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfContato;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
    
    private void setFornecedor(JSONObject fornecedor) {   
        this.fornecedor = fornecedor;
        tfCodigo.setText(fornecedor.getString("codigo"));
        tfNome.setText(fornecedor.getString("nome"));
        tfCNPJ.setText(fornecedor.getString("cnpj"));
        tfEmail.setText(fornecedor.getString("email"));
        tfContato.setText(fornecedor.getString("contato"));
    }

    @Override
    public void salvar() {
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        try {
            this.mainframe.setStatus("Salvando registro. Aguarde...");
            
            //Altera valor do objeto Fornecedor
            fornecedor.put("nome", tfNome.getText());
            fornecedor.put("codigo", tfCodigo.getText());
            fornecedor.put("cnpj", tfCNPJ.getText().replace(".", "").replace("/", "").replace("-", ""));
            fornecedor.put("email", tfEmail.getText());
            fornecedor.put("contato", tfContato.getText());
           
            try {
                BackendService.save("fornecedores", this.fornecedor);
                this.mainframe.setStatus("Pronto!");
            } catch (Exception e) {
                this.fail = true;
                
                TasDialogError dlgError = new TasDialogError(mainframe);
                dlgError.showError(TasDialogError.DANGER_ERROR, 
                                   "<html>Não foi possível salvar o registro. Clique em \"Detalhes\" Para visualizar o problema.</html>", 
                                   e.getMessage());
                this.mainframe.setStatus(new ImageIcon(getClass().getResource("/assets/system/icons/icon-warning-small.png")), 
                                             e.getMessage(), "Ops!");
                
            }
           
        } finally {
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            dispose();
        }
    }

    @Override
    public void validarDados() throws NotValidateException {
        
        this.fieldsEmpty = new ArrayList<>();
        
        if (tfCodigo.getText().equals("")) {
            this.fieldsEmpty.add("O campo \"Código\" deve ser preenchido.");
        }
        if (tfNome.getText().equals("")) {
            this.fieldsEmpty.add("O campo \"Nome\" deve ser preenchido.");
        }
        if (tfCNPJ.getText().equals("")) {
            this.fieldsEmpty.add("O campo \"CNPJ\" deve ser preenchido.");
        }
        if (tfEmail.getText().equals("")) {
            this.fieldsEmpty.add("O campo \"Email\" deve ser preenchido.");
        }
        if (tfContato.getText().equals("")) {
            this.fieldsEmpty.add("O campo \"Contato\" deve ser preenchido.");
        }
        
        //Verifica se ocorreu erro
        if (this.fieldsEmpty.size() > 0)
            throw new NotValidateException("<html>Alguns campos obrigatórios não foram preenchidos! Corrija e tente novamente.</html>");
        
    }
}
