package br.edu.materdei.tas.desktop.dialog;

import br.edu.materdei.tas.desktop.MainFrame;
import br.edu.materdei.tas.desktop.exception.NotValidateException;
import br.edu.materdei.tas.desktop.gui.core.MonetarioDocument;
import br.edu.materdei.tas.desktop.gui.core.TasDialogError;
import br.edu.materdei.tas.desktop.service.BackendService;

import java.awt.Component;
import java.awt.Cursor;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JList;
import net.sf.json.JSONObject;


public class ItemCompraDialog extends GenericDialogImpl {
    private JSONObject item;
    
    /**
     * Creates new form TasDialogConfirm
     * @param parent
     */
    public ItemCompraDialog(java.awt.Frame parent) {
        super(parent, true);
        
        this.mainframe = (MainFrame) parent;
        
        initComponents();
        
        //Carrega os grupos
        loadProdutos();
        
        //Faz com que seja mostrado no componente o atributo nome
        cbProduto.setRenderer( new DefaultListCellRenderer(){

            @Override  
            public Component getListCellRendererComponent(JList list, Object value, int index,
                    boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index,
                isSelected, cellHasFocus);

                if ((value != null)&&(value instanceof JSONObject)) {
                    JSONObject provedor = (JSONObject) value;
                    setText( provedor.getString("nome"));
                }
                
                return this;
            }
        });
        
        tfVlrIUnit.setDocument(new MonetarioDocument());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        barraTitulo = new javax.swing.JPanel();
        divTop = new javax.swing.JPanel();
        plLeft = new javax.swing.JPanel();
        plRight = new javax.swing.JPanel();
        divBottom = new javax.swing.JPanel();
        container1 = new javax.swing.JPanel();
        close = new br.edu.materdei.tas.desktop.gui.titlebar.TasCloseButton();
        titulo = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox();
        tfQtdade = new javax.swing.JTextField();
        tfVlrIUnit = new javax.swing.JTextField();
        tfVlrTotal = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botoes = new javax.swing.JPanel();
        cancelar = new br.edu.materdei.tas.desktop.gui.core.TasDialogButton();
        salvar = new br.edu.materdei.tas.desktop.gui.core.TasDialogButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        container.setBackground(new java.awt.Color(246, 246, 246));
        container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 64, 34)));
        container.setLayout(new java.awt.BorderLayout());

        barraTitulo.setOpaque(false);
        barraTitulo.setPreferredSize(new java.awt.Dimension(348, 34));
        barraTitulo.setLayout(new java.awt.BorderLayout());

        divTop.setOpaque(false);
        divTop.setPreferredSize(new java.awt.Dimension(10, 7));

        javax.swing.GroupLayout divTopLayout = new javax.swing.GroupLayout(divTop);
        divTop.setLayout(divTopLayout);
        divTopLayout.setHorizontalGroup(
            divTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        divTopLayout.setVerticalGroup(
            divTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        barraTitulo.add(divTop, java.awt.BorderLayout.NORTH);

        plLeft.setOpaque(false);
        plLeft.setPreferredSize(new java.awt.Dimension(5, 10));

        javax.swing.GroupLayout plLeftLayout = new javax.swing.GroupLayout(plLeft);
        plLeft.setLayout(plLeftLayout);
        plLeftLayout.setHorizontalGroup(
            plLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        plLeftLayout.setVerticalGroup(
            plLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        barraTitulo.add(plLeft, java.awt.BorderLayout.WEST);

        plRight.setOpaque(false);
        plRight.setPreferredSize(new java.awt.Dimension(5, 10));

        javax.swing.GroupLayout plRightLayout = new javax.swing.GroupLayout(plRight);
        plRight.setLayout(plRightLayout);
        plRightLayout.setHorizontalGroup(
            plRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        plRightLayout.setVerticalGroup(
            plRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        barraTitulo.add(plRight, java.awt.BorderLayout.EAST);

        divBottom.setOpaque(false);
        divBottom.setPreferredSize(new java.awt.Dimension(10, 6));

        javax.swing.GroupLayout divBottomLayout = new javax.swing.GroupLayout(divBottom);
        divBottom.setLayout(divBottomLayout);
        divBottomLayout.setHorizontalGroup(
            divBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        divBottomLayout.setVerticalGroup(
            divBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        barraTitulo.add(divBottom, java.awt.BorderLayout.SOUTH);

        container1.setOpaque(false);
        container1.setPreferredSize(new java.awt.Dimension(277, 21));
        container1.setLayout(new java.awt.BorderLayout());

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        container1.add(close, java.awt.BorderLayout.EAST);

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Adicionar Produto");
        container1.add(titulo, java.awt.BorderLayout.CENTER);

        barraTitulo.add(container1, java.awt.BorderLayout.CENTER);

        container.add(barraTitulo, java.awt.BorderLayout.NORTH);

        content.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Produto");

        cbProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProdutoActionPerformed(evt);
            }
        });

        tfQtdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfQtdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfQtdadeKeyReleased(evt);
            }
        });

        tfVlrIUnit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfVlrIUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfVlrIUnitKeyReleased(evt);
            }
        });

        tfVlrTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        tfVlrTotal.setEnabled(false);
        tfVlrTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Qtdade.");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Vlr. Unit.");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Vlr. Total");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfQtdade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfVlrTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(tfVlrIUnit))
                        .addGap(0, 229, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQtdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVlrIUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfVlrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        container.add(content, java.awt.BorderLayout.CENTER);

        botoes.setOpaque(false);
        botoes.setPreferredSize(new java.awt.Dimension(10, 50));
        botoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 10, 10));

        cancelar.setButtonType(br.edu.materdei.tas.desktop.gui.core.TasDialogButton.DialogButtonType.DANGER_BUTTON);
        cancelar.setLabel("Cancelar");
        cancelar.setPreferredSize(new java.awt.Dimension(75, 30));
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarMousePressed(evt);
            }
        });
        botoes.add(cancelar);

        salvar.setButtonType(br.edu.materdei.tas.desktop.gui.core.TasDialogButton.DialogButtonType.SUCCESS_BUTTON);
        salvar.setLabel("OK");
        salvar.setPreferredSize(new java.awt.Dimension(75, 30));
        salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salvarMousePressed(evt);
            }
        });
        botoes.add(salvar);

        container.add(botoes, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMousePressed
        dispose();
    }//GEN-LAST:event_cancelarMousePressed

    private void salvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMousePressed
        try {
            validarDados();
            salvar();
        } catch (NotValidateException e) {
            TasDialogError dlgWarning = new TasDialogError(mainframe);
            dlgWarning.showError(TasDialogError.WARNING_ERROR, 
                                 "Preenchimento obrigatório", 
                                 e.getMessage(), 
                                 this.fieldsEmpty);
        }
    }//GEN-LAST:event_salvarMousePressed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        dispose();
    }//GEN-LAST:event_closeMousePressed

    private void cbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdutoActionPerformed
        selecionarProduto();
    }//GEN-LAST:event_cbProdutoActionPerformed

    private void tfQtdadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQtdadeKeyReleased
        atualizaTotal();
    }//GEN-LAST:event_tfQtdadeKeyReleased

    private void tfVlrIUnitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVlrIUnitKeyReleased
        atualizaTotal();
    }//GEN-LAST:event_tfVlrIUnitKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraTitulo;
    private javax.swing.JPanel botoes;
    private br.edu.materdei.tas.desktop.gui.core.TasDialogButton cancelar;
    private javax.swing.JComboBox cbProduto;
    private br.edu.materdei.tas.desktop.gui.titlebar.TasCloseButton close;
    private javax.swing.JPanel container;
    private javax.swing.JPanel container1;
    private javax.swing.JPanel content;
    private javax.swing.JPanel divBottom;
    private javax.swing.JPanel divTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel plLeft;
    private javax.swing.JPanel plRight;
    private br.edu.materdei.tas.desktop.gui.core.TasDialogButton salvar;
    private javax.swing.JTextField tfQtdade;
    private javax.swing.JTextField tfVlrIUnit;
    private javax.swing.JFormattedTextField tfVlrTotal;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
    
    public JSONObject getItem() {
        return item;
    }
    
    private void selecionarProduto() {
        if (cbProduto.getModel().getSelectedItem() instanceof JSONObject) {
            JSONObject produto = (JSONObject) cbProduto.getModel().getSelectedItem();
            if (produto.get("preco") != null) {
                DecimalFormat df = new DecimalFormat("#.00");
                String preco = df.format(produto.getDouble("preco"));
                tfVlrIUnit.setText(preco.replace(",", ""));
            }
            
            tfQtdade.requestFocus();
        }
    }

    private void atualizaTotal() {
        Integer qtdade = 0;
        if (!tfQtdade.getText().equals("")) {
            qtdade = Integer.valueOf(tfQtdade.getText());
        }
        
        Double vlrunit = 0.0;
        if (!tfVlrIUnit.getText().equals("")) {
            vlrunit = Double.valueOf(tfVlrIUnit.getText().replace(".", "").replace(",", "."));
        }
        
        tfVlrTotal.setValue((qtdade * vlrunit));        
    }

    private void loadProdutos() {
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        try {
            this.mainframe.setStatus("Carregando produtos. Aguarde...");
           
            try {
                Object[] produtos = BackendService.findAll("produtos");
                
                cbProduto.removeAllItems();
                for (Object object : produtos) {
                    JSONObject produto = (JSONObject) object;
                    cbProduto.addItem(produto);
                }
                this.mainframe.setStatus("Pronto!");
            } catch (Exception e) {
                this.fail = true;
                
                TasDialogError dlgError = new TasDialogError(mainframe);
                dlgError.showError(TasDialogError.DANGER_ERROR, 
                                   "<html>Não foi possível carregar os Produtos. Clique em \"Detalhes\" Para visualizar o problema.</html>", 
                                   e.getMessage());
                this.mainframe.setStatus(new ImageIcon(getClass().getResource("/assets/system/icons/icon-warning-small.png")), 
                                             e.getMessage(), "Ops!");
                dispose();
            }
           
        } finally {
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }
    
    @Override
    public void salvar() {
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        try {
            this.item = new JSONObject();
            
            //Produto
            JSONObject produto = (JSONObject) cbProduto.getModel().getSelectedItem();
            item.put("produto", produto);
            
            //Qtdade
            Integer qtdade = Integer.valueOf(tfQtdade.getText());
            item.put("qtdade", qtdade);
            
            //Valor Unit.
            String aux = tfVlrIUnit.getText().replace(".", "");
            Double vlrunit = Double.valueOf(aux.replace(",", "."));
            item.put("vlrunit", vlrunit);
           
        } finally {
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            dispose();
        }
    }

    @Override
    public void validarDados() throws NotValidateException {
        
        this.fieldsEmpty = new ArrayList<>();
        
        if (cbProduto.getModel().getSelectedItem() == null) {
            this.fieldsEmpty.add("O campo \"Produto\" deve ser preenchido.");
        }
        if (tfQtdade.getText().equals("")) {
            this.fieldsEmpty.add("O campo \"Qtdade.\" deve ser preenchido.");
        }
        if (tfVlrIUnit.getText().equals("")) {
            this.fieldsEmpty.add("O campo \"Vlr. Unit.\" deve ser preenchido.");
        }
    }
}
