package br.edu.materdei.tas.desktop.gui.core;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.ImageIcon;


public class TasDialogError extends javax.swing.JDialog {
    public static final int WARNING_ERROR = 0;
    public static final int DANGER_ERROR = 1;
    
    private final Dimension normal = new Dimension(480, 220);
    private final Dimension expandido = new Dimension(480, 350);
    private boolean contraido;
    
    /**
     * Creates new form TasDialogError
     * @param parent
     */
    public TasDialogError(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        
        this.contraido = true;
        panelDetail.setVisible(false);
        
        this.dispose();
        this.setLocationRelativeTo(parent);
        this.setUndecorated(true);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        barraTitulo = new javax.swing.JPanel();
        divTop = new javax.swing.JPanel();
        plLeft = new javax.swing.JPanel();
        plRight = new javax.swing.JPanel();
        divBottom = new javax.swing.JPanel();
        conteudoTitle = new javax.swing.JPanel();
        close = new br.edu.materdei.tas.desktop.gui.titlebar.TasCloseButton();
        titulo = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        panelNormal = new javax.swing.JPanel();
        icone = new javax.swing.JLabel();
        mensagem = new javax.swing.JLabel();
        panelDetail = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        detalhe = new javax.swing.JTextArea();
        botoes = new javax.swing.JPanel();
        panelEsq = new javax.swing.JPanel();
        btDetalhe = new br.edu.materdei.tas.desktop.gui.core.TasDialogButton();
        panelDir = new javax.swing.JPanel();
        ok = new br.edu.materdei.tas.desktop.gui.core.TasDialogButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 300));
        setMinimumSize(new java.awt.Dimension(480, 220));
        setPreferredSize(new java.awt.Dimension(480, 220));

        container.setBackground(new java.awt.Color(246, 246, 246));
        container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 64, 34)));
        container.setLayout(new java.awt.BorderLayout());

        barraTitulo.setOpaque(false);
        barraTitulo.setPreferredSize(new java.awt.Dimension(348, 34));
        barraTitulo.setLayout(new java.awt.BorderLayout());

        divTop.setOpaque(false);
        divTop.setPreferredSize(new java.awt.Dimension(10, 7));

        javax.swing.GroupLayout divTopLayout = new javax.swing.GroupLayout(divTop);
        divTop.setLayout(divTopLayout);
        divTopLayout.setHorizontalGroup(
            divTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        divTopLayout.setVerticalGroup(
            divTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        barraTitulo.add(divTop, java.awt.BorderLayout.NORTH);

        plLeft.setOpaque(false);
        plLeft.setPreferredSize(new java.awt.Dimension(5, 10));

        javax.swing.GroupLayout plLeftLayout = new javax.swing.GroupLayout(plLeft);
        plLeft.setLayout(plLeftLayout);
        plLeftLayout.setHorizontalGroup(
            plLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        plLeftLayout.setVerticalGroup(
            plLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        barraTitulo.add(plLeft, java.awt.BorderLayout.WEST);

        plRight.setOpaque(false);
        plRight.setPreferredSize(new java.awt.Dimension(5, 10));

        javax.swing.GroupLayout plRightLayout = new javax.swing.GroupLayout(plRight);
        plRight.setLayout(plRightLayout);
        plRightLayout.setHorizontalGroup(
            plRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        plRightLayout.setVerticalGroup(
            plRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        barraTitulo.add(plRight, java.awt.BorderLayout.EAST);

        divBottom.setOpaque(false);
        divBottom.setPreferredSize(new java.awt.Dimension(10, 6));

        javax.swing.GroupLayout divBottomLayout = new javax.swing.GroupLayout(divBottom);
        divBottom.setLayout(divBottomLayout);
        divBottomLayout.setHorizontalGroup(
            divBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        divBottomLayout.setVerticalGroup(
            divBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        barraTitulo.add(divBottom, java.awt.BorderLayout.SOUTH);

        conteudoTitle.setOpaque(false);
        conteudoTitle.setPreferredSize(new java.awt.Dimension(277, 21));
        conteudoTitle.setLayout(new java.awt.BorderLayout());

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        conteudoTitle.add(close, java.awt.BorderLayout.EAST);

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conteudoTitle.add(titulo, java.awt.BorderLayout.CENTER);

        barraTitulo.add(conteudoTitle, java.awt.BorderLayout.CENTER);

        container.add(barraTitulo, java.awt.BorderLayout.NORTH);

        content.setOpaque(false);
        content.setLayout(new java.awt.BorderLayout(10, 0));

        panelNormal.setMinimumSize(new java.awt.Dimension(66, 50));
        panelNormal.setOpaque(false);
        panelNormal.setPreferredSize(new java.awt.Dimension(166, 70));
        panelNormal.setRequestFocusEnabled(false);
        panelNormal.setLayout(new java.awt.BorderLayout());

        icone.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icone.setPreferredSize(new java.awt.Dimension(100, 0));
        panelNormal.add(icone, java.awt.BorderLayout.WEST);

        mensagem.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mensagem.setText("mensagem");
        panelNormal.add(mensagem, java.awt.BorderLayout.CENTER);

        content.add(panelNormal, java.awt.BorderLayout.NORTH);

        panelDetail.setOpaque(false);

        detalhe.setEditable(false);
        detalhe.setBackground(new java.awt.Color(229, 229, 229));
        detalhe.setColumns(20);
        detalhe.setRows(5);
        scroll.setViewportView(detalhe);

        javax.swing.GroupLayout panelDetailLayout = new javax.swing.GroupLayout(panelDetail);
        panelDetail.setLayout(panelDetailLayout);
        panelDetailLayout.setHorizontalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDetailLayout.setVerticalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        content.add(panelDetail, java.awt.BorderLayout.CENTER);

        container.add(content, java.awt.BorderLayout.CENTER);

        botoes.setOpaque(false);
        botoes.setPreferredSize(new java.awt.Dimension(10, 50));
        botoes.setLayout(new java.awt.BorderLayout());

        panelEsq.setOpaque(false);
        panelEsq.setPreferredSize(new java.awt.Dimension(100, 52));

        btDetalhe.setButtonType(br.edu.materdei.tas.desktop.gui.core.TasDialogButton.DialogButtonType.DEFAULT_BUTTON);
        btDetalhe.setLabel("Detalhes");
        btDetalhe.setPreferredSize(new java.awt.Dimension(75, 30));
        btDetalhe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btDetalheMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelEsqLayout = new javax.swing.GroupLayout(panelEsq);
        panelEsq.setLayout(panelEsqLayout);
        panelEsqLayout.setHorizontalGroup(
            panelEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(panelEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEsqLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDetalhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        panelEsqLayout.setVerticalGroup(
            panelEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
            .addGroup(panelEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEsqLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDetalhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        botoes.add(panelEsq, java.awt.BorderLayout.WEST);

        panelDir.setOpaque(false);

        ok.setButtonType(br.edu.materdei.tas.desktop.gui.core.TasDialogButton.DialogButtonType.DEFAULT_BUTTON);
        ok.setLabel("OK");
        ok.setPreferredSize(new java.awt.Dimension(75, 30));
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                okMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelDirLayout = new javax.swing.GroupLayout(panelDir);
        panelDir.setLayout(panelDirLayout);
        panelDirLayout.setHorizontalGroup(
            panelDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDirLayout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDirLayout.setVerticalGroup(
            panelDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botoes.add(panelDir, java.awt.BorderLayout.CENTER);

        container.add(botoes, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void btDetalheMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDetalheMousePressed
        if (this.contraido)
            showDetails();
        else 
            closeDetails();
    }//GEN-LAST:event_btDetalheMousePressed

    private void okMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMousePressed
        dispose();
    }//GEN-LAST:event_okMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraTitulo;
    private javax.swing.JPanel botoes;
    private br.edu.materdei.tas.desktop.gui.core.TasDialogButton btDetalhe;
    private br.edu.materdei.tas.desktop.gui.titlebar.TasCloseButton close;
    private javax.swing.JPanel container;
    private javax.swing.JPanel content;
    private javax.swing.JPanel conteudoTitle;
    private javax.swing.JTextArea detalhe;
    private javax.swing.JPanel divBottom;
    private javax.swing.JPanel divTop;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel mensagem;
    private br.edu.materdei.tas.desktop.gui.core.TasDialogButton ok;
    private javax.swing.JPanel panelDetail;
    private javax.swing.JPanel panelDir;
    private javax.swing.JPanel panelEsq;
    private javax.swing.JPanel panelNormal;
    private javax.swing.JPanel plLeft;
    private javax.swing.JPanel plRight;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
    
    private void showDetails() {
        this.contraido = false;
        setPreferredSize(expandido);
        panelDetail.setVisible(true);
        btDetalhe.setLabel("Ocultar");
        pack();
    }
    
    private void closeDetails() {
        this.contraido = true;
        setPreferredSize(normal);
        panelDetail.setVisible(false);
        btDetalhe.setLabel("Detalhes");
        pack();
    }
    public void showError(int errorType, String message, String detail) {
        ArrayList<String> details = new ArrayList<>();
        details.add(detail);
        showError(errorType, "Ocorreu um Erro", message, details);
    }
    public void showError(int errorType, String title, String message, ArrayList<String> details) {
        titulo.setText(title);
        mensagem.setText(message);
        detalhe.setRows(details.size());
        for (String detail : details) {
            detalhe.append(detail+"\n");
        }
        
        //Icone 
        if (errorType == DANGER_ERROR) {
            icone.setIcon(new ImageIcon(getClass().getResource("/assets/system/icons/icon-error.png")));
        } else {
            icone.setIcon(new ImageIcon(getClass().getResource("/assets/system/icons/icon-warning.png")));
        }
        
        this.setVisible(true);
    }
}
