package br.edu.materdei.tas.desktop.gui.core;

import javax.swing.ImageIcon;


public class TasSeparadorItem extends TasImagePanel {

    /**
     * Creates new form TasSeparadorItem
     */
    public TasSeparadorItem() {
        initComponents();
        this.setImage(new ImageIcon(getClass().getResource("/assets/toolbar/fundoSeparadorItem.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(10, 78));
        setMinimumSize(new java.awt.Dimension(10, 78));
        setPreferredSize(new java.awt.Dimension(10, 78));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
